# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocketIO-NewExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocketIO-NewExample
  
  pod 'VideoSDKRTC', :git => 'https://github.com/videosdk-live/videosdk-rtc-ios-sdk.git', :branch => 'fix/crash'

end
